START TRANSACTION;

ALTER TABLE `users`
CHANGE COLUMN `created`
`created` TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP();

ALTER TABLE `messages`
CHANGE COLUMN `created`
`created` TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP();

ALTER TABLE `reactions`
CHANGE COLUMN `created`
`created` TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP();

ALTER TABLE `voicechannellog`
CHANGE COLUMN `join_time`
`join_time` TIMESTAMP NOT NULL DEFAULT UTC_TIMESTAMP();

COMMIT;
